version: 1.0.0
services:
  docker_react:
    build: 
      context: ./docker_react/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: docker_react
    volumes:
      - ./docker_react:/docker_react
      - node_modules:/docker_react/node_modules
volumes:
  node_modules:
